"""Create article relations table

Revision ID: 9cc4d08d75c7
Revises: bd02e35a2fbe
Create Date: 2026-09-01 17:41:38.945276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc4d08d75c7'
down_revision: Union[str, Sequence[str], None] = 'bd02e35a2fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_relations',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('related_article_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'related_article_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_relations')
    # ### end Alembic commands ###
